settings:
  keyb_path: "$HOME/.config/keyb/keyb.yml"
  debug: false
  reverse: false
  mouse: true
  search_mode: false
  sort_keys: false
  title: ""
  prompt: 'keys > '
  prompt_location: "top"
  placeholder: '...'
  prefix_sep: ;
  sep_width: 4
  margin: 0
  padding: 1
  border: hidden
color:
  prompt: ""
  cursor_fg: ""
  cursor_bg: ""
  filter_fg: "#FFA066"
  filter_bg: ""
  border_color: ""
keys:
  quit: q, ctrl+c
  up: k, up
  down: j, down
  up_focus: ctrl+k
  down_focus: ctrl+j
  half_up: ctrl+u
  half_down: ctrl+d
  full_up: ctrl+b
  full_bottom: ctrl+f
  first_line: g
  last_line: G
  top: H
  middle: M
  bottom: L
  search: /
  clear_search: alt+d
  normal: esc
  cursor_word_forward: "alt+right, alt+f"
  cursor_word_backward: "alt+left, alt+b"
  cursor_delete_word_backward: "alt+backspace"
  cursor_delete_word_forward: "alt+delete"
  cursor_delete_after_cursor: "alt+k"
  cursor_delete_before_cursor: "alt+u"
  cursor_line_start: "home, ctrl+a"
  cursor_line_end: "end, ctrl+e"
  cursor_paste: "ctrl+v"
